services:
  mittwald-ddns:
    image: ghcr.io/betheltraun/mittwald-ddns:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MITTWALD_CONFIG_PATH: /config/mittwald-ddns.json
      MITTWALD_SECRET: ${MITTWALD_SECRET:-}
      MITTWALD_IP_SERVICE_URL: ${MITTWALD_IP_SERVICE_URL:-https://api64.ipify.org}
    volumes:
      - ./config:/config
